bugfix: Add write and read lock on RealtimeLuceneTextIndex to keep t…
apache/pinot pull request #10620
Opened 2023-04-15 10:17 UTC by INNOCENT-BOY

bugfix: Add write and read lock on RealtimeLuceneTextIndex to keep t…

Our team create an Text Index for one column. When the amount of concurrency is small, there is no problem with the query. However as the amount of concurrency increases, various problems caused by concurrency will now pop up. Then we will add write/read lock to LuceneTextIndex.

2023-04-15 15:19 UTC, mayankshriv commented
Any performance numbers to share, given that this can lead to high thread contention for high throughput use cases?

2023-04-15 16:14 UTC, INNOCENT-BOY commented
@mayankshriv Hi we haven't have any test numbers now，but we used the same lock with other index，such as inverted index that submitted by @Jackie-Jiang

2023-04-15 18:17 UTC, Jackie-Jiang approved these changes
The fix looks good. Have you verified this in your environment?

2023-04-16 16:05 UTC, INNOCENT-BOY commented
> The fix looks good. Have you verified this in your environment?

Hi @Jackie-Jiang ,although i tried some ways to add readwritelock to lucenetextindex,  it doesn't work.  Currently the only way to avoid generating parseException is to add ReentrantLock. But as we all know, that is not a perfect way, especially handling a lots of read requests. I will continue to debug this issue. And If you have any good idea, please let me know.

2023-04-17 00:34 UTC, Jackie-Jiang requested changes
Interesting.. `ReentrantReadWriteLock` itself should be re-entrant. We cannot use regular lock because that will make read path single-threaded.
You might want to check if the read part is thread safe

2023-04-18 12:30 UTC, INNOCENT-BOY commented
Hi @Jackie-Jiang , I perfomed lots of tests. The reason why report parseException is not thread content between read threads and write thread. The root cause is QueryParser is not thread safe, so we can't share QueryParser instance between all request on the same consuming segment. And I have given an suitable solution. Each request on consuming segments that have text index will generate their own QueryParser instance. This instance will destroy after parse. This parse is very fast. So this fix vesion can't bring burden to JVM memory. Meanwhile it won't make read path single-threaded. Hope your review and reply, @Jackie-Jiang .

2023-04-18 16:59 UTC, INNOCENT-BOY commented
> Hi @Jackie-Jiang , I performed lots of tests. The reason why report parseException is not thread content between read threads and write thread. The root cause is QueryParser is not thread safe, so we can't share QueryParser instance between all request on the same consuming segment. And I have given an suitable solution. Each request on consuming segments that have text index will generate their own QueryParser instance. This instance will destroy after executing parse statement. The speed of parse is very fast. So this fix vesion won't bring burden to JVM memory. Meanwhile it won't make read path single-threaded. Hope your review and reply, @Jackie-Jiang .

<img width="708" alt="image" src="https://user-images.githubusercontent.com/38196564/232850363-5ab117dc-7f81-426d-b970-ff54d4032290.png">

2023-04-18 21:34 UTC, Jackie-Jiang approved these changes

2023-04-18 21:34 UTC, merged